name: Docker image build
env:
  username: ${{secrets.DOCKERHUB_USERNAME}}
  password: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKER_IMAGE_SELENIUM: selenium
  DOCKER_IMAGE_NODE: chrome
  RUNN: ubuntu-latest
  ENN: dev
  
on:    
  workflow_dispatch:

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: login to docker hub
          if: ${{ ${{env.ENN}} == 'dev'}}
          run: |
            docker login -u $username -p $password
            echo ${{ env.RUNN }}
            
            
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la
            echo "1"
            echo "1"
            echo "$username/$DOCKER_IMAGE_SELENIUM"
            echo "$username/$DOCKER_IMAGE_NODE"
            docker images
            
