name: github_action_syntax_checking

env:
  username: ${{secrets.DOCKERHUB_USERNAME}}
  password: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKER_IMAGE_SELENIUM: selenium
  DOCKER_IMAGE_NODE: chrome
  
on:
  workflow_dispatch:
  
jobs:
    build:
    
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
          with:
             repository: sachin193959/HelloWorldMaven@master

        - name: ls
          run: ls -ltra
        

        
            
