name: github_action_syntax_checking

env:
  username: ${{secrets.DOCKERHUB_USERNAME}}
  password: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKER_IMAGE_SELENIUM: selenium
  DOCKER_IMAGE_NODE: chrome
  
on:
 schedule:
   - cron: '1/1 * * * *'
jobs:
    build:
    
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@master
          with:
             repository: sachin193959/HelloWorldMaven

        - name: ls
          run: ls -ltra
        

        
            
