name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
            DOCKER_IMAGE_SELENIUM: selenium
            DOCKER_IMAGE_NODE: chrome
            
          run: |
            docker login -u $username -p $password
            
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la
            echo ${{env.DOCKER_IMAGE_SELENIUM}}"
            echo "${{env.DOCKER_IMAGE_NODE}}"
            docker build -t sachin193959/selenium selenium/Hub/.
            docker build -t sachin193959/node selenium/NodeChrome/.
            docker images
            
        - name: push the docker image
          id: push-docker-image
          run: |
            docker push sachin193959/selenium:latest
            docker push sachin193959/node:latest

        - name: Trivy docker images scanning
          run: |
            cd /usr/local/bin
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.16.0
            trivy sachin193959/selenium:latest
            trivy sachin193959/node:latest

        
            
