name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Start xvfb (for headless browser)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 & export DISPLAY=:99

      - name: Run Selenium tests
        run: |
          cd python
          pytest
